# Generated by Django 2.1.3 on 2018-11-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_calendar', '0002_auto_20181126_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
