# Generated by Django 2.1.3 on 2018-11-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_calendar', '0003_event_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='intro',
            field=models.CharField(blank=True, max_length=250, verbose_name='Event description'),
        ),
    ]
